[package]
name = "nix-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
surrealdb.workspace = true
tokio.workspace = true
serde.workspace = true
chrono.workspace = true
nanoid.workspace = true
