[package]
name = "nix-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "list-roots"
path = "src/bin/list_roots.rs"

[dependencies]
nix-core = { path = "../../crates/nix-core" }
tokio = { version = "1.0", features = ["full"] }